# Generated by Django 5.0.2 on 2024-02-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_quizcreator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcreator',
            name='username',
            field=models.CharField(default='something', max_length=200),
        ),
    ]
